export const MEDIA_QUERY_END_POINT = {
  LARGE: "2560px",
  DESKTOP: "1920px",
  TABLET1: "1200px",
  TABLET2: "1100px",
  TABLET3: "991px",
  MOBILE1: "767px",
  MOBILE2: "640px",
};

export const ROUTES = [
  {
    ID: 0,
    PATH: "/jobsfeed",
    LABEL: "채용",
    NEW: false,
    BETA: false,
  },
  {
    ID: 1,
    PATH: "/events",
    LABEL: "이벤트",
    NEW: false,
    BETA: false,
  },
  {
    ID: 2,
    PATH: "/salary",
    LABEL: "직군별 연봉",
    NEW: false,
    BETA: false,
  },
  {
    ID: 3,
    PATH: "/cv/list",
    LABEL: "이력서",
    NEW: false,
    BETA: false,
  },
  {
    ID: 4,
    PATH: "/community/48",
    LABEL: "커뮤니티",
    NEW: true,
    BETA: false,
  },
  {
    ID: 5,
    PATH: "/gigs/experts",
    LABEL: "프리랜서",
    NEW: false,
    BETA: false,
  },
  {
    ID: 6,
    PATH: "/aiscore/resume",
    LABEL: "AI 합격예측",
    NEW: false,
    BETA: true,
  },
];

export const carouselData = [
  {
    ID: 0,
    SRC: "https://static.wanted.co.kr/images/banners/1436/e2dd9445.jpg",
    TITLE: "마케터를 위한 데이터",
    SUB: "잘 나가는 마케터는 무엇이 다를까!?",
    PATH: "#",
  },
  {
    ID: 1,
    SRC: "https://static.wanted.co.kr/images/banners/1435/6cdcea85.jpg",
    TITLE: "유저 경험을 설계하라!",
    SUB: "문제를 해결하는 프로덕트 디자인",
    PATH: "#",
  },
  {
    ID: 2,
    SRC: "https://static.wanted.co.kr/images/banners/1473/41f7b36e.jpg",
    TITLE: "나도 개발자 되고 싶다",
    SUB: "프론트엔드 무료 교육과정 참여하기",
    PATH: "#",
  },
  {
    ID: 3,
    SRC: "https://static.wanted.co.kr/images/banners/1453/7a978579.jpg",
    TITLE: "리크루터 커리어 가이드",
    SUB: "싼마이 리크루터가 되지 않기 위해",
    PATH: "#",
  },
  {
    ID: 4,
    SRC: "https://static.wanted.co.kr/images/banners/1452/be4ec643.jpg",
    TITLE: "Git? GitHub?",
    SUB: "협업 필수 도구 마스터하기",
    PATH: "#",
  },
  {
    ID: 5,
    SRC: "https://static.wanted.co.kr/images/banners/1451/725c6862.jpg",
    TITLE: "믿을 것은 데이터 뿐!",
    SUB: "요즘 데이터팀은 어떻게 일할까?",
    PATH: "#",
  },
  {
    ID: 6,
    SRC: "https://static.wanted.co.kr/images/banners/1434/fdbbcb06.jpg",
    TITLE: "요즘 MD가 일하는 방법",
    SUB: "실무자가 공개하는 MD 커리어의 모든 것!",
    PATH: "#",
  },
  {
    ID: 7,
    SRC: "https://static.wanted.co.kr/images/banners/1454/e504b006.jpg",
    TITLE: "아는 만큼 보인다!",
    SUB: "노동법 '채용' 시리즈",
    PATH: "#",
  },
  {
    ID: 8,
    SRC: "https://static.wanted.co.kr/images/banners/1438/015566ac.jpg",
    TITLE: "스타벅스 굿즈 좋아하세요?",
    SUB: "사랑받는 디자인의 비밀",
    PATH: "#",
  },
  {
    ID: 9,
    SRC: "https://static.wanted.co.kr/images/banners/1468/3df61cbc.jpg",
    TITLE: "해, 커리어 EP 02 공개",
    SUB: "최종 발표를 위한 마지막 관문 2라운드의 승자는?",
    PATH: "#",
  },
  {
    ID: 10,
    SRC: "https://static.wanted.co.kr/images/banners/1460/619f3af7.jpg",
    TITLE: "개발자 성장 비결 공개!",
    SUB: "글 쓰는 개발자들의 이야기",
    PATH: "#",
  },
  {
    ID: 11,
    SRC: "https://static.wanted.co.kr/images/banners/1436/e2dd9445.jpg",
    TITLE: "마케터를 위한 데이터",
    SUB: "잘 나가는 마케터는 무엇이 다를까!?",
    PATH: "#",
  },
  {
    ID: 12,
    SRC: "https://static.wanted.co.kr/images/banners/1435/6cdcea85.jpg",
    TITLE: "유저 경험을 설계하라!",
    SUB: "문제를 해결하는 프로덕트 디자인",
    PATH: "#",
  },
  {
    ID: 13,
    SRC: "https://static.wanted.co.kr/images/banners/1473/41f7b36e.jpg",
    TITLE: "나도 개발자 되고 싶다",
    SUB: "프론트엔드 무료 교육과정 참여하기",
    PATH: "#",
  },
  {
    ID: 14,
    SRC: "https://static.wanted.co.kr/images/banners/1453/7a978579.jpg",
    TITLE: "리크루터 커리어 가이드",
    SUB: "싼마이 리크루터가 되지 않기 위해",
    PATH: "#",
  },
  {
    ID: 15,
    SRC: "https://static.wanted.co.kr/images/banners/1452/be4ec643.jpg",
    TITLE: "Git? GitHub?",
    SUB: "협업 필수 도구 마스터하기",
    PATH: "#",
  },
  {
    ID: 16,
    SRC: "https://static.wanted.co.kr/images/banners/1451/725c6862.jpg",
    TITLE: "믿을 것은 데이터 뿐!",
    SUB: "요즘 데이터팀은 어떻게 일할까?",
    PATH: "#",
  },
  {
    ID: 17,
    SRC: "https://static.wanted.co.kr/images/banners/1434/fdbbcb06.jpg",
    TITLE: "요즘 MD가 일하는 방법",
    SUB: "실무자가 공개하는 MD 커리어의 모든 것!",
    PATH: "#",
  },
  {
    ID: 18,
    SRC: "https://static.wanted.co.kr/images/banners/1454/e504b006.jpg",
    TITLE: "아는 만큼 보인다!",
    SUB: "노동법 '채용' 시리즈",
    PATH: "#",
  },
  {
    ID: 19,
    SRC: "https://static.wanted.co.kr/images/banners/1438/015566ac.jpg",
    TITLE: "스타벅스 굿즈 좋아하세요?",
    SUB: "사랑받는 디자인의 비밀",
    PATH: "#",
  },
  {
    ID: 20,
    SRC: "https://static.wanted.co.kr/images/banners/1468/3df61cbc.jpg",
    TITLE: "해, 커리어 EP 02 공개",
    SUB: "최종 발표를 위한 마지막 관문 2라운드의 승자는?",
    PATH: "#",
  },
  {
    ID: 21,
    SRC: "https://static.wanted.co.kr/images/banners/1460/619f3af7.jpg",
    TITLE: "개발자 성장 비결 공개!",
    SUB: "글 쓰는 개발자들의 이야기",
    PATH: "#",
  },
];
